### PR TITLE
Added client.droplets.listByTag and updated documentation

### PR DESCRIPTION
**Pull request by pheebcodes**
This adds the function `client.droplets.listByTag` and updates documentation to add `client.droplets.listByTag`, as well as fixes the documentation by changing `client.droplets.deleteByTagName` to `client.droplets.deleteByTag`.

### CODE REVIEW

**Comment by pheebcodes** [comment]
Found a bug in the code. Give me a moment and I'll fix that as well as add a test for the function.

Edit: Never mind. It appears to work like the `client.droplets.list` function works.

**Comment by phillbaker** [comment]
@chncdcksn thanks for the PR! 

I think this might also be doable via:

```
var tag = 'foo';
client.droplets.list({ tag_name: tag }, callback)
```

Would you mind cherry-picking 5867d94de4786a6d13848109854689b166157d8b into a separate PR?

**Comment by pheebcodes** [comment]
It is doable like that, however you aren't able to do `client.droplets.list({ tag_name: tag })` and get a promise returned. Maybe there should be a check to see if `callback` is an object or a function, using it as the params if it's an object or a callback if it's a function?

Edit: Removed the documentation fix commit and will put it in a separate pull request.

**Comment by phillbaker** [comment]
@chncdcksn we'd need to either add a few tests for this new function or add the conditional as you suggest to detect in the `list` function whether it's an object or function. I'd probably vote for the latter, but what do you think?

**Comment by phillbaker** [comment]
@chncdcksn I've pushed a fix in 7a65d428feeb65be2c3229941ea3727c59cedbde and released a new version, what do you think of closing this PR for now?

**Comment by pheebcodes** [comment]
That works! Thanks!

**Pull request closed without merging**
