### PR TITLE
Documentation fix

### PR DESCRIPTION
**Pull request by omgimanerd**

### CODE REVIEW

**Comment by omgimanerd** [comment]
Should there be two getAction() methods for the two types of page queries?

**Comment by phillbaker** [comment]
Thanks! 

`getAction()` should only ever return one item I think? So no need for paging?

**Comment by omgimanerd** [comment]
Huh, there are query options for the getAction() under the Image Resources.

**Comment by phillbaker** [comment]
Ah! That's also wrong, those shouldn't be there! Good catch!

**Pull request merged**
