### PR TITLE
Fix for #12 since volume detaching returns 202

### PR DESCRIPTION
**Pull request by omgimanerd**
According to the DigitalOcean documentation, volume attaching, detaching, and resizing return a 202 status code.
Let me know if this should be solved a different way. I'm still not entirely familiar with the codebase.

### CODE REVIEW

**Comment by omgimanerd** [comment]
The unit tests failed after 3ecb4cde5312447e865119a01a9a26ae86cb3762, so I updated them appropriately. Please let me know if I overlooked something.

**Comment by phillbaker** [comment]
Great, thanks! Can you squash your commits?

**Comment by omgimanerd** [comment]
Sure thing, did I miss anything?

**Comment by phillbaker** [comment]
Looks good, thanks. I'll get a version bump out.

**Comment by omgimanerd** [comment]
Could you release this on npm please?

**Comment by phillbaker** [comment]
Whoops, pushed!

**Pull request merged**
